import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-intermodal-accessorial-invoice-audit",
  "engine": "recovery",
  "title": "Intermodal Accessorial Invoice Audit",
  "shortTitle": "Intermodal Accessorial Invoice Audit",
  "tagline": "Validate intermodal storage, lifts, chassis, and terminal accessorials against event timelines and contract responsibility.",
  "industry": "Intermodal Spend Recovery",
  "buyer": "Shippers, 3PLs, and intermodal marketing companies",
  "uiPort": 4698,
  "apiPort": 5698,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Intermodal Accessorial Invoice Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits in one accountable workflow. Validate intermodal storage, lifts, chassis, and terminal accessorials against event timelines and contract responsibility.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Intermodal Accessorial Invoice Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("provider-contract-library","IAI01","Provider contract library","Execute provider contract library using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed provider contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Provider contract library Reference","text","IAI01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]}),
feature("shipment-container-registry","IAI02","Shipment container registry","Execute shipment container registry using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed shipment container registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Shipment container registry Reference","text","IAI02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]}),
feature("rail-event-ingestion","IAI03","Rail event ingestion","Execute rail event ingestion using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed rail event ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Rail event ingestion Reference","text","IAI03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]}),
feature("terminal-event-timeline","IAI04","Terminal event timeline","Execute terminal event timeline using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed terminal event timeline decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Terminal event timeline Reference","text","IAI04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]}),
feature("appointment-evidence","IAI05","Appointment evidence","Execute appointment evidence using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed appointment evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Appointment evidence Reference","text","IAI05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]}),
feature("free-time-calculation","IAI06","Free-time calculation","Execute free-time calculation using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed free-time calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Free-time calculation Reference","text","IAI06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]}),
feature("storage-charge-audit","IAI07","Storage charge audit","Execute storage charge audit using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed storage charge audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Storage charge audit Reference","text","IAI07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]}),
feature("lift-charge-validation","IAI08","Lift charge validation","Execute lift charge validation using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed lift charge validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Lift charge validation Reference","text","IAI08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]}),
feature("chassis-responsibility","IAI09","Chassis responsibility","Execute chassis responsibility using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed chassis responsibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Chassis responsibility Reference","text","IAI09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]}),
feature("flip-split-validation","IAI10","Flip split validation","Execute flip split validation using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed flip split validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Flip split validation Reference","text","IAI10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]}),
feature("drayage-linkage","IAI11","Drayage linkage","Execute drayage linkage using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed drayage linkage decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Drayage linkage Reference","text","IAI11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]}),
feature("invoice-recalculation","IAI12","Invoice recalculation","Execute invoice recalculation using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed invoice recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Invoice recalculation Reference","text","IAI12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]}),
feature("provider-dispute-package","IAI13","Provider dispute package","Execute provider dispute package using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed provider dispute package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Provider dispute package Reference","text","IAI13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]}),
feature("credit-reconciliation","IAI14","Credit reconciliation","Execute credit reconciliation using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Credit reconciliation Reference","text","IAI14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]}),
feature("terminal-provider-analytics","IAI15","Terminal provider analytics","Execute terminal provider analytics using contracts, rail waybills, container events, appointments, free time, storage, lifts, chassis, drayage, invoices, disputes, and credits.","Produce a governed terminal provider analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Intermodal Shipment","text","Provider / Intermodal Shipment · Standard Case"],["caseReference","Terminal provider analytics Reference","text","IAI15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1263750],["supportedAmount","Evidence-Supported Amount","currency",1061550],["domainDriver","Accessorial Type","select","Storage",["Storage","Lift","Chassis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Provider contract library case","Shipment container registry case","Rail event ingestion case","Terminal event timeline case","Appointment evidence case"]})
]);
